@startuml
服务器端 <- 客户端  : 加密方法 encipher 排序块长度 1 ~ 10（客户端输入）
服务器端 -> 客户端  : 服务器端判断加密方法一致情况下 服务器端生成随机秘钥 1 ~ 10
服务器端 <- 客户端  : 需要加密的数据, 目前固定数据，已经写了文件读和写，后续可以从文件中读取发送
服务器端 -> 客户端  : 服务器端加密，换序，然后发送给客户端，客户端收到后换序解密就是原始发送的数据（打印验证）
@enduml